### ISSUE TITLE
Coloured output is not handled 

### ISSUE THREAD

**Issue by lipi** [numaru/vscode-ceedling-test-adapter#102]
When enabling Unity's coloured_report plugin, which turns pass/fail results green/red, the test explorer's output doesn't handle the control characters:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/358404/171330158-fbf84fa5-b55d-4283-a27a-43c244a5584a.png">

Expected behaviour:  at least it should remove the control characters from the output.  Ideally it would colour the output properly. 

Note, that VSCode's terminal does handle the colours properly:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/358404/171331548-613322cd-9ad5-4fe8-ac38-ecf8b60ff237.png">

**Comment by numaru** [comment]
👍 Thank you for the clear report. I will have a look!

**Comment by numaru** [comment]
After a quick investigation. The text is given to the output panel GUI using a `vscode.OutputChannel`. And adding the ascii color support to the native output panel has been removed from the vscode roadmap. But you can use for the [IBM/output-colorizer]( https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer) extension to add ascii color to the output.

What I can do is: remove the escape codes by default and add a settings option to re-enable them if you use a third-party extension like the IBM one.

**Comment by lipi** [comment]
I have tried the IBM plugin but it seems to add extra coloring for certain keywords, it does not improve on the original issue.

**Comment by numaru** [comment]
Oups, my bad :facepalm: I tested the extension really quick and I lost myself. But, we can now remove the escape codes in any case :smile:

**Comment by numaru** [comment]
It should be now fixed in the new 1.10.0 release
