### ISSUE TITLE
Tests do not load after upgrade to 1.10.0

### ISSUE THREAD

**Issue by tkaier** [numaru/vscode-ceedling-test-adapter#105]
In the Side panel, no tests show up with the version v1.10.0

This is the case for native Windows and WSL. After downgrading the Ceedling test adapter plugin to v1.9.1 the tests reappear.

**Comment by numaru** [comment]
Thank you for the report! 

:facepalm: I confess! I changed some import syntax in the release branch and did not even test on my machine...

![sorry-cat-crying](https://www.meme-arsenal.com/memes/f81d1b654ccf3073d7427c0b1889ccaf.jpg)

**Comment by py4mac** [comment]
Thanks for the update.

**Comment by tkaier** [comment]
Thank you for the update.

I love your plugin and use it on a daily basis. And I am impressed by the fast response time to this issue. So many thanks for your work.
