### ISSUE TITLE
Error while debugging test: Error: Method not implemented.

### ISSUE THREAD

**Issue by aenima1891** [numaru/vscode-ceedling-test-adapter#12]
Hello,
I'm trying to debug a test, but I receive this message from VSCODE
![immagine](https://user-images.githubusercontent.com/1100887/46862525-52960a80-ce15-11e8-94b4-dfec9698c04c.png)

I've ceedling, gcc, g++, gdb in my System PATH environment variable.

Thank you for the help

**Comment by numaru** [comment]
Yes, the debug feature is not implemented for now 😉

**Comment by aenima1891** [comment]
I'm debugging each test using task.json to compile the test (GCC) and launch.json to debug (gdb).
It's not the easiest way, but It works.
I Hope you'll implement this feature soon.
😁

**Comment by numaru** [comment]
I'm closing this because the debug feature is now available (since [v1.2.0](https://github.com/numaru/vscode-ceedling-test-adapter/blob/master/CHANGELOG.md#120---2019-02-12))
