### ISSUE TITLE
project.yml env variables support

### ISSUE THREAD

**Issue by WJKPK** [numaru/vscode-ceedling-test-adapter#132]
During the development of a project that requires the setup of an environment-dependent build path, I encountered a minor issue. When the build_root in `project.yml` is configured with the following statement in the project.yml file:
``` project.yml
  :build_root: "#{ENV['BUILD_DIR']}/unit-tests"
```
an anomaly is observed in the test result icons, which appear as warnings, regardless of the actual test results. You can see an example screenshot here:
![Screenshot from 2024-02-12 15-14-42](https://github.com/numaru/vscode-ceedling-test-adapter/assets/43456158/8b31b3db-da59-4f85-a610-12c536f6ea3e)
Even when the test results are positive, as indicated in the test summary:
```
Test 'test_lcd_manager.c'
-------------------------
Running test_lcd_manager.out...

--------------------
OVERALL TEST SUMMARY
--------------------
TESTED:  3
PASSED:  3
FAILED:  0
IGNORED: 0
```
It appears that Ruby expressions similar to the one mentioned above are officially supported in Ceedling. An example can be found in the [Ceedling blinky](https://github.com/ThrowTheSwitch/Ceedling/blob/master/examples/blinky/project.yml) project. However, it seems that this syntax is not supported in the test adapter. To address this, a [patch](https://github.com/numaru/vscode-ceedling-test-adapter/files/14239536/patch.txt) has been created. Does this code meet the requirements to be merged into the project? Should I make any changes before submitting a pull request? EDIT: Already created PR for convenience #133

A big thanks in advance for the feedback!

**Comment by numaru** [comment]
I tried to improve a bit what you already propose in the PR #133 by using the ruby cli to evaluate the ruby strings. But the feature must be enabled using the `ceedlingExplorer.evalRubyInStrings: true` config.

ref: 172b24595025987ffc0bbf214886d79da10ba9e3.

Thank you for the detailed report and the working solution :smiley:
