### ISSUE TITLE
Test Explorer always reloading tests

### ISSUE THREAD

**Issue by thiagoperroni** [numaru/vscode-ceedling-test-adapter#2]
The UI stays on this state forever. The workspace has only a ceedling initial project with only one test. I got no problems running tests over the terminal.

![image](https://user-images.githubusercontent.com/15650735/46321938-a5252a80-c5bc-11e8-9dee-f5526f558fc2.png)

**Comment by numaru** [comment]
In which terminal do you use Ceedling?
For now the ext use 'cmd.exe' as default shell. Also Ceedling (and gcc by default) must be accessible in this shell to get the list of test (and execute them later).

**Comment by thiagoperroni** [comment]
Sorry for the delay.

I use Ceedling on 'cmd.exe'. Using `shellPath` option as default (null),  the problem is the same I reported previously. 

Configuring `shellPath`  with the 'cmd.exe' path, I got this new error:

![image](https://user-images.githubusercontent.com/15650735/46581985-0020ac80-ca17-11e8-8f85-a8842ec4afa3.png)

At least it has an error message now. I'll try some more things before give up.

Thanks for your attention

**Comment by numaru** [comment]
Thanks, i was able to reproduce it and patch it ✌. You should now be able to run from cmd.exe (`shellPath` not set). If one of you can confirm, I will let this issue closed.

**Comment by aenima1891** [comment]
It works! Thank you!

**Comment by thiagoperroni** [comment]
It worked for me too! Thank you so much!
