### ISSUE TITLE
When xml and junit test report is enabled plugin doesn't work

### ISSUE THREAD

**Issue by OlegSomov** [numaru/vscode-ceedling-test-adapter#20]
When `xml_tests_report` and `junit_tests_report` is enabled the extension doesn't work, it stuck on the testing stage.
![image](https://user-images.githubusercontent.com/19969581/58715907-d77a6800-8395-11e9-93b1-5ef82fa22467.png)
 
Removing `junit_tests_report` makes it work again.

```
:plugins:
  :load_paths:
    - vendor/ceedling/plugins
  :enabled:
    - xml_tests_report
    - junit_tests_report
    - stdout_pretty_tests_report
    - module_generator
    - raw_output_report
    - gcov
```

**Comment by numaru** [comment]
This seems fixed by ThrowTheSwitch/Ceedling#324. Since it require the last (and unreleased) version of ceedling, a disclaimer should be appended to the README.md of this repo.
