### ISSUE TITLE
can not run *.out files on windows

### ISSUE THREAD

**Issue by Oliverleo123** [numaru/vscode-ceedling-test-adapter#33]
Hello,

command:ceedlingExplorer.debugTestExecutable always expects to find an *out.file
On windows there are *.exe files.
There must be a way to change from *.out to *.exe

Edit:
changing the exension variable in the ceedling project.yml to .out actually works.

Suggestion:; this extension should look for the variable `executable` in the project.yml and set the ending of the command `ceedlingExplorer.debugTestExecutable` accordingly

**Comment by numaru** [comment]
Thanks for reporting the issue. It should be fixed in the next release :relaxed:
