### ISSUE TITLE
unable to open test file (Error: file not found) while debugging, but the test runs and terminates anyway

### ISSUE THREAD

**Issue by UG-Steven** [numaru/vscode-ceedling-test-adapter#34]
My tests run fine when I run them normally. When I debug I get this error even though the terminal still shows test output. Interestingly enough, I can set breakpoints, it will wait at the breakpoint and I can tell it to continue but I can't see what line the debugger is on. Every time I click on the topmost line in the call stack, the error disappears and instantly reappears. 

The location it is trying to load the test file from is where it used to be, but I move the whole ceedling project into another folder when I started using visual code. But I can't seem to figure out why it is trying to read the source test file from this location. I used the debugger configuration from [here](https://marketplace.visualstudio.com/items?itemName=numaru.vscode-ceedling-test-adapter&ssr=false#overview) and I only changed the debugger path. If I mess around with the other settings there the process stops with an error much sooner.

![Here is what it looks like when I try to debug](https://user-images.githubusercontent.com/52240670/63601682-33840f80-c5c6-11e9-8917-efb6df25436f.png)

**Comment by numaru** [comment]
It looks like some of binaries still contain path to old src directory in their debug symbols. Running a `ceedling clean` in the moved project should fix the issue.
