### ISSUE TITLE
Support for other VS distribution, eg Atmel Studio

### ISSUE THREAD

**Issue by srdjastankovic** [numaru/vscode-ceedling-test-adapter#45]
HI,

I tried to install .vsix file into Win10 with installed AtmelStudio7 and got following log:

1/9/2020 2:52:26 PM - Microsoft VSIX Installer
1/9/2020 2:52:26 PM - -------------------------------------------
1/9/2020 2:52:26 PM - Initializing Install...
1/9/2020 2:52:26 PM - Extension Details...
1/9/2020 2:52:26 PM - 	Identifier      : vscode-ceedling-test-adapter
1/9/2020 2:52:26 PM - 	Name            : Ceedling Test Explorer
1/9/2020 2:52:26 PM - 	Author          : numaru
1/9/2020 2:52:26 PM - 	Version         : 1.4.2
1/9/2020 2:52:26 PM - 	Description     : Run your Ceedling tests in the Sidebar of Visual Studio Code
1/9/2020 2:52:26 PM - 	Locale          : en-US
1/9/2020 2:52:26 PM - 	MoreInfoURL     : 
1/9/2020 2:52:26 PM - 	InstalledByMSI  : False
1/9/2020 2:52:26 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
1/9/2020 2:52:26 PM - 
1/9/2020 2:52:26 PM - 	Supported Products : 
1/9/2020 2:52:26 PM - 		Microsoft.VisualStudio.Code
1/9/2020 2:52:26 PM - 			Version : 
1/9/2020 2:52:26 PM - 
1/9/2020 2:52:26 PM - 	References      : 
1/9/2020 2:52:26 PM - 
1/9/2020 2:52:26 PM - Searching for applicable products...
1/9/2020 2:52:27 PM - Found installed product - Global Location
1/9/2020 2:52:27 PM - Found installed product - AtmelStudio
1/9/2020 2:52:27 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()

So, problem is cause because AtmelStudio isn't supported. Is it possible or do you plan to support AtmelStudio?

Thanks in advance

**Comment by numaru** [comment]
I could be wrong but, unfortunately, I don't think vscode extensions are designed to be compatible with other IDEs.
