### ISSUE TITLE
How to configure ceedling command line

### ISSUE THREAD

**Issue by thomasfinchbr** [numaru/vscode-ceedling-test-adapter#48]
Hi,

First of all thanks for the great plugin.
I would like to know how I can configure ceedling plugin in vs code to run the command line
ceedling gcov:all

I understand that it always runs the option ceedling test:all.

Thanks.

**Comment by numaru** [comment]
Yes you are right. It is not possible to run `ceedling gcov` in the extension for now. Is there a benefit to run `gcov` instead of `test`?

**Comment by thomasfinchbr** [comment]
I run the option 'ceedling gcov:all utils:gcov' to get code coverage of the unit tests. 
Whit this option the output is a little different.
I get a xml with the code coverage that can but used with another vs code plugin.
I think that it is not possible to the coverage with the option 'test:all'

Thanks.

**Comment by numaru** [comment]
✨ It's now implemented as a `ceedlingExplorer.testCommandArgs` option. I share a config in the PR to use [Coverage Gutters](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters).

Thank you for the contribution. 😺

**Comment by thomasfinchbr** [comment]
Thanks. I will test it!
