### ISSUE TITLE
Test Explorer Output in Visual Studio Code : Failed to find the project.yml file. Please check the ceedlingExplorer.projectPath option.

### ISSUE THREAD

**Issue by AdrianWenger1988** [numaru/vscode-ceedling-test-adapter#80]
Hi,

I cannot run the tests in Visual Code:
Followin error message appears:

Failed to find the project.yml file. Please check the ceedlingExplorer.projectPath option.

![image](https://user-images.githubusercontent.com/43845512/108981090-aaeba100-768c-11eb-8f8c-01d7bf352a29.png)

But there actually is a project.yml file in the current dir:

![image](https://user-images.githubusercontent.com/43845512/108983831-9230ba80-768f-11eb-877d-9bc3e298bec2.png)

![image](https://user-images.githubusercontent.com/43845512/108981170-c191f800-768c-11eb-94b6-4a4bbd79c1ec.png)

tools:
![image](https://user-images.githubusercontent.com/43845512/108981582-25b4bc00-768d-11eb-878a-8f28cd7310f2.png)

![image](https://user-images.githubusercontent.com/43845512/108981620-306f5100-768d-11eb-8cb1-38c2777bdbd3.png)

![image](https://user-images.githubusercontent.com/43845512/108983613-572e8700-768f-11eb-927e-560440962f3a.png)

**Comment by AdrianWenger1988** [comment]
The problem is repsoducable.
My colleague faces the same issue!

**Comment by numaru** [comment]
Hello, it is working on my windows machine and I don't see obvious reason to fail in the code. But this message can happen also if the file exists but it can't load the content. I suspect a wrong project.yml file encoding. The expected file encoding is UTF-8. The encoding error message is not logged but you can try to use the extension with a clean project to see if it fixes the issue.

Usually, I use `ceedling example temp_sensor` to generate a project. Then I open the project.yml with vscode (make sure the file encoding is UTF-8 in the right bottom corner) and add `xml_tests_report` to the `plugin.enabled` section. I configure the `ceedlingExplorer.shellPath` option if ceedling is not accessible in my default shell and reload the tests.

**Comment by AdrianWenger1988** [comment]
Thanks for your reply.
It is not the enconding of the project.yml, but there is an issue with the project.yml file content of the  seetings for gcov:

Settings which lead to the issue:
![image](https://user-images.githubusercontent.com/43845512/108993237-91e9ec80-769a-11eb-9ff1-243e1c18758c.png)

It works with this settings:
![image](https://user-images.githubusercontent.com/43845512/108993126-69fa8900-769a-11eb-8198-3aa1c3551de9.png)

**Comment by numaru** [comment]
Ok, perfect. I can close this. 👌
